version: "3"
services:
  server:
    image: chaymaguesmi/backend
    ports:
      - "8089:8089"
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    ports:
      - "3306:3306"

    environment:
      - MYSQL_DATABASE=devopsdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=chayma
      - MYSQL_PASSWORD=1234
networks:
  springmysql-net: